### ISSUE TITLE
The .zip file of the protobuf compiler should not be downloaded from Google Code

### ISSUE THREAD

**Issue by lsb** [ninjudd/lein-protobuf#12]
Google Code is shutting down, wompwomp

**Comment by lsb** [comment]
Also downloading it over SSL seems like a good idea too

**Comment by MitchellJThomas** [comment]
Looks to me like this is fixed in 4882e509f3eb3a862f88b768f0ae56705359d2d2

**Comment by lsb** [comment]
:+1: :tada:
