### ISSUE TITLE
Protobuf java files are not included during javac compilation

### ISSUE THREAD

**Issue by MitchellJThomas** [ninjudd/lein-protobuf#17]
When running `lein protobuf` with .proto files in the default directory (resources/proto), after protoc has successfully completed, the java compiler step fails with errors such as: 

```
error: cannot find symbol
    com.google.protobuf.ProtocolStringList
                       ^
  symbol:   class ProtocolStringList
  location: package com.google.protobuf
```

For this issue, everything was at the latest versions

 :plugins [[lein-protobuf "0.4.3"]
 :dependencies [[org.clojure/clojure "1.7.0"][org.flatland/protobuf "0.8.1"]]

**Comment by MitchellJThomas** [comment]
Ok, so a _partial_ solution is to include com.google.protobuf/protobuf-java in my project's dependencies e.g. `[com.google.protobuf/protobuf-java "2.6.1"]`   

I (incorrectly) assumed Google Protobuf classes would "pulled in" by either this project (lien-protobuf) or by the org.flatland/protobuf project... I suppose the later would be more natural.

When I "go back" to using :plugins [lein-protobuf "0.4.1"] and  :dependencies [[org.clojure/clojure "1.7.0"][org.flatland/protobuf "0.8.1"]], I don't need to include the google protobuf and `lien protobuf` just works.

**Comment by echeran** [comment]
Thanks for the report & reminder.  I included this information in documentation that appears on the repo main page.  In the update, I also added a little table that tells which version of Protobuf is the default installation version for lein-protobuf.

It looks like Protobuf 3.0 is going to come out soon.  After the final 3.0 release comes out, if you notice before me, feel free to give me a heads up and I can bump the relevant versions.

In the meantime, with the 0.5.0 release, you should be able to tell lein-protobuf to use a protoc executable from a custom location.
