### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by straxus** [ninjudd/lein-protobuf#5]
There's no apparent open source license on this project, so terms of use (and extension and etc) are a bit unclear at the moment. Is this project meant to be licensed under the EPL like e.g. clojure-protobuf?

**Comment by MitchellJThomas** [comment]
Seems like this was fixed in 4882e509f3eb3a862f88b768f0ae56705359d2d2

**Comment by echeran** [comment]
@MitchellJThomas  Yes, you are correct.  Closing out, now.
